/**
 * KTO Daily Spending Baseline Dashboard
 * Reads live data from /data/ JSON files generated by the pipeline.
 * Falls back to sample data if files are not yet available.
 */

const { useState, useEffect, useMemo } = React;

// ── Constants ─────────────────────────────────────────────────────────────────
const COHORTS = [
  { id: "whale",   label: "Whale",   vip: "VIP 12+",  color: "#F0997B", dim: "#4A1B0C", bg: "rgba(240,153,123,0.08)", border: "rgba(240,153,123,0.2)" },
  { id: "dolphin", label: "Dolphin", vip: "VIP 7–11", color: "#5DCAA5", dim: "#04342C", bg: "rgba(93,202,165,0.08)",   border: "rgba(93,202,165,0.2)"  },
  { id: "minnow",  label: "Minnow",  vip: "VIP 0–6",  color: "#85B7EB", dim: "#042C53", bg: "rgba(133,183,235,0.08)", border: "rgba(133,183,235,0.2)" },
];

// ── Data loading ──────────────────────────────────────────────────────────────
async function loadJSON(path) {
  try {
    const r = await fetch(path);
    if (!r.ok) return null;
    return await r.json();
  } catch { return null; }
}

async function loadCSV(path) {
  try {
    const r = await fetch(path);
    if (!r.ok) return null;
    const text = await r.text();
    const lines = text.trim().split("\n");
    if (lines.length < 2) return [];
    const headers = lines[0].split(",").map(h => h.trim());
    return lines.slice(1).map(line => {
      const vals = line.split(",");
      const obj = {};
      headers.forEach((h, i) => {
        const v = vals[i]?.trim();
        obj[h] = isNaN(v) || v === "" ? v : Number(v);
      });
      return obj;
    });
  } catch { return null; }
}

// ── Formatters ────────────────────────────────────────────────────────────────
function fmt(v) {
  if (v == null) return "–";
  if (v >= 1e9) return (v / 1e9).toFixed(1) + "B";
  if (v >= 1e6) return (v / 1e6).toFixed(1) + "M";
  if (v >= 1e3) return (v / 1e3).toFixed(0) + "K";
  return v.toLocaleString();
}

function fmtVND(v) {
  if (v == null) return "–";
  if (v >= 1e9) return (v / 1e9).toFixed(1) + "B ₫";
  if (v >= 1e6) return (v / 1e6).toFixed(0) + "M ₫";
  return v.toLocaleString() + " ₫";
}

// ── Reusable components ───────────────────────────────────────────────────────
function Card({ children, style }) {
  return (
    <div style={{
      background: "rgba(255,255,255,0.025)",
      border: "1px solid rgba(255,255,255,0.06)",
      borderRadius: 10,
      ...style,
    }}>{children}</div>
  );
}

function MetricCard({ label, value, sub, accent, wide }) {
  return (
    <Card style={{
      padding: "14px 18px",
      flex: wide ? "1 1 200px" : "1 1 140px",
      minWidth: wide ? 200 : 130,
      ...(accent ? { borderColor: accent + "44" } : {}),
    }}>
      <div style={{ fontSize: 11, color: "#8a8a8a", letterSpacing: 0.3, marginBottom: 6, textTransform: "uppercase" }}>{label}</div>
      <div style={{ fontSize: 22, fontWeight: 600, color: accent || "#e8e8e8", letterSpacing: -0.5 }}>{value}</div>
      {sub && <div style={{ fontSize: 11, color: "#666", marginTop: 4 }}>{sub}</div>}
    </Card>
  );
}

function Spark({ vals, color, w = 140, h = 36 }) {
  if (!vals || vals.length < 2) return null;
  const clean = vals.filter(v => v != null);
  const mn = Math.min(...clean) * 0.96;
  const mx = Math.max(...clean) * 1.04;
  const rng = mx - mn || 1;
  const pts = clean.map((v, i) => `${4 + i * ((w - 8) / (clean.length - 1))},${h - 4 - ((v - mn) / rng) * (h - 8)}`).join(" ");
  return (
    <svg viewBox={`0 0 ${w} ${h}`} style={{ width: "100%", display: "block" }}>
      <polyline points={pts} fill="none" stroke={color} strokeWidth={1.5} strokeLinecap="round" strokeLinejoin="round" />
      {clean.map((v, i) => (
        <circle key={i} cx={4 + i * ((w - 8) / (clean.length - 1))} cy={h - 4 - ((v - mn) / rng) * (h - 8)} r={2} fill={color} />
      ))}
    </svg>
  );
}

function SectionHead({ num, title, desc, color }) {
  return (
    <div style={{ marginBottom: 14 }}>
      <div style={{ display: "flex", alignItems: "center", gap: 10 }}>
        <div style={{ width: 22, height: 22, borderRadius: 6, background: color + "18", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 11, fontWeight: 700, color }}>{num}</div>
        <div style={{ fontSize: 15, fontWeight: 600, color: "#e0e0e0" }}>{title}</div>
      </div>
      {desc && <div style={{ fontSize: 12, color: "#666", marginTop: 4, paddingLeft: 32 }}>{desc}</div>}
    </div>
  );
}

// ── Trend chart (SVG, no library) ─────────────────────────────────────────────
function TrendChart({ data }) {
  const W = 640, H = 210, PL = 44, PR = 8, PT = 24, PB = 28;
  const cw = W - PL - PR, ch = H - PT - PB;

  const all = data.flatMap(d => [d.actual, d.upper, d.lower].filter(v => v != null));
  if (!all.length) return null;
  const mx = Math.max(...all) * 1.05;
  const mn = Math.min(...all) * 0.92;

  const xi = i => PL + (i / (data.length - 1)) * cw;
  const yi = v => PT + (1 - (v - mn) / (mx - mn)) * ch;

  const band = data.map((d, i) => `${i === 0 ? "M" : "L"}${xi(i)},${yi(d.upper || d.baseline)}`).join(" ") +
    data.slice().reverse().map((d, i) => `L${xi(data.length - 1 - i)},${yi(d.lower || d.baseline)}`).join(" ") + "Z";
  const bl = data.map((d, i) => `${i === 0 ? "M" : "L"}${xi(i)},${yi(d.baseline)}`).join(" ");
  const ac = data.map((d, i) => `${i === 0 ? "M" : "L"}${xi(i)},${yi(d.actual)}`).join(" ");

  const evStart = data.findIndex(d => d.is_event);
  const evEnd   = data.length - 1 - [...data].reverse().findIndex(d => d.is_event);

  return (
    <svg viewBox={`0 0 ${W} ${H}`} style={{ width: "100%", display: "block" }}>
      {[0.25, 0.5, 0.75].map(f => {
        const val = mn + (mx - mn) * (1 - f);
        return (
          <g key={f}>
            <line x1={PL} y1={PT + f * ch} x2={W - PR} y2={PT + f * ch} stroke="rgba(255,255,255,0.05)" strokeWidth={0.5} />
            <text x={PL - 6} y={PT + f * ch + 4} textAnchor="end" fontSize={10} fill="#555">
              {val >= 1e6 ? (val / 1e6).toFixed(1) + "M" : (val / 1e3).toFixed(0) + "K"}
            </text>
          </g>
        );
      })}
      {evStart >= 0 && evStart !== data.length - 1 && (
        <>
          <rect x={xi(evStart)} y={PT} width={xi(evEnd) - xi(evStart)} height={ch} fill="rgba(239,159,39,0.06)" rx={3} />
          <text x={(xi(evStart) + xi(evEnd)) / 2} y={PT + 14} textAnchor="middle" fontSize={10} fill="#EF9F27" fontWeight={500}>Event</text>
        </>
      )}
      <path d={band} fill="rgba(133,183,235,0.07)" />
      <path d={bl} fill="none" stroke="rgba(133,183,235,0.3)" strokeWidth={1} strokeDasharray="4 3" />
      <path d={ac} fill="none" stroke="#85B7EB" strokeWidth={2} />
      {data.map((d, i) => d.signal && d.signal !== "ok" ? (
        <circle key={i} cx={xi(i)} cy={yi(d.actual)} r={3.5} fill={d.signal === "over" ? "#5DCAA5" : "#F0997B"} />
      ) : null)}
      {data.filter((_, i) => i % 5 === 0 || i === data.length - 1).map((d, _, arr) => {
        const i = data.indexOf(d);
        return <text key={i} x={xi(i)} y={H - 6} textAnchor="middle" fontSize={10} fill="#555">{d.label}</text>;
      })}
    </svg>
  );
}

// ── Main Dashboard ─────────────────────────────────────────────────────────────
function Dashboard() {
  const [metrics, setMetrics] = useState(null);
  const [forecast, setForecast] = useState(null);
  const [alerts, setAlerts] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    Promise.all([
      loadCSV("/data/daily_metrics.csv"),
      loadJSON("/data/forecast.json"),
      loadJSON("/data/alerts.json"),
    ]).then(([m, f, a]) => {
      if (!m) { setError("data/daily_metrics.csv not found — run the pipeline first."); }
      setMetrics(m);
      setForecast(f);
      setAlerts(a);
      setLoading(false);
    });
  }, []);

  const EMPTY = { trendData: [], ydAll: {}, cohortRows: COHORTS.map(c => ({ c })), velData: COHORTS.map(c => ({ c, vals: [], trend: "stable" })), spenderData: COHORTS.map(c => ({ c, vals: [], newVals: [] })), shopData: [], reportDate: "–", dataDate: "–" };

  const { trendData, ydAll, cohortRows, velData, spenderData, shopData, reportDate, dataDate } = useMemo(() => {
    if (!metrics || !metrics.length) return EMPTY;

    const allDates = [...new Set(metrics.map(r => r.ds))].sort();
    const latestDate = allDates[allDates.length - 1];
    const last30 = allDates.slice(-30);

    // Aggregate across cohorts per date
    const byDate = {};
    metrics.forEach(r => {
      if (!byDate[r.ds]) byDate[r.ds] = { actual: 0, baseline: 0, upper: 0, lower: 0, is_event: false, signals: [] };
      byDate[r.ds].actual    += r.total_gold_spent || 0;
      byDate[r.ds].baseline  += r.baseline_p50      || 0;
      byDate[r.ds].upper     += r.baseline_upper    || 0;
      byDate[r.ds].lower     += r.baseline_lower    || 0;
      if (r.event_flag) byDate[r.ds].is_event = true;
      if (r.signal) byDate[r.ds].signals.push(r.signal);
    });

    const trendData = last30.map(ds => {
      const d = new Date(ds);
      const row = byDate[ds] || {};
      const signals = row.signals || [];
      const signal = signals.includes("over") ? "over" : signals.includes("under") ? "under" : "ok";
      return {
        ds, label: `${d.getDate()}/${d.getMonth() + 1}`,
        actual: row.actual, baseline: row.baseline,
        upper: row.upper, lower: row.lower,
        is_event: row.is_event, signal,
      };
    });

    const ydAll = byDate[latestDate] || {};

    // Latest per cohort
    const cohortRows = COHORTS.map(c => {
      const row = metrics.find(r => r.ds === latestDate && r.cohort === c.id) || {};
      return { c, ...row };
    });

    // 7-day velocity sparklines
    const last7 = allDates.slice(-7);
    const velData = COHORTS.map(c => {
      const vals = last7.map(ds => {
        const r = metrics.find(m => m.ds === ds && m.cohort === c.id);
        return r?.balance_velocity ?? null;
      });
      const trend = vals.length >= 2 && vals[vals.length - 1] < vals[0] ? "declining" : "stable";
      return { c, vals, trend };
    });

    const spenderData = COHORTS.map(c => {
      const vals    = last7.map(ds => metrics.find(m => m.ds === ds && m.cohort === c.id)?.active_spenders ?? null);
      const newVals = last7.map(ds => metrics.find(m => m.ds === ds && m.cohort === c.id)?.new_spenders ?? null);
      return { c, vals, newVals };
    });

    // Shop breakdown (latest date, all cohorts combined)
    const shopMap = {};
    metrics.filter(r => r.ds === latestDate).forEach(r => {
      // logway_group not available in daily_metrics — use logway from shop_breakdown if loaded
      // Placeholder: aggregate spend by cohort for demo
    });

    const d = new Date(latestDate);
    d.setDate(d.getDate() + 1);
    const reportDate = d.toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" });
    const dataDate   = new Date(latestDate).toLocaleDateString("en-GB", { day: "numeric", month: "short", year: "numeric" });

    return { trendData, ydAll, cohortRows, velData, spenderData, shopData: [], reportDate, dataDate };
  }, [metrics]);

  if (loading) {
    return (
      <div style={{ fontFamily: "monospace", color: "#555", padding: 40, background: "#0c0c0e", minHeight: "100vh" }}>
        Loading data…
      </div>
    );
  }

  if (error) {
    return (
      <div style={{ fontFamily: "monospace", color: "#F0997B", padding: 40, background: "#0c0c0e", minHeight: "100vh" }}>
        <strong>Pipeline data not available</strong><br /><br />
        {error}<br /><br />
        Run: <code>bash pipeline/run_pipeline.sh</code>
      </div>
    );
  }

  const ydActual   = ydAll?.actual   || 0;
  const ydBaseline = ydAll?.baseline || 0;
  const deviation  = ydBaseline ? ((ydActual - ydBaseline) / ydBaseline * 100).toFixed(1) : "–";
  const devAbs     = parseFloat(deviation);
  const devColor   = isNaN(devAbs) ? "#666" : Math.abs(devAbs) > 25 ? "#F0997B" : Math.abs(devAbs) > 15 ? "#EF9F27" : "#5DCAA5";

  const totalSpenders = cohortRows.reduce((s, r) => s + (r.active_spenders || 0), 0);
  const forecastRows  = (forecast?.cohorts?.whale || forecast?.cohorts?.dolphin)
    ? (() => {
        const dates = (forecast?.cohorts?.whale || []).map(r => r.date);
        return dates.map(ds => {
          const whale   = (forecast?.cohorts?.whale   || []).find(r => r.date === ds) || {};
          const dolphin = (forecast?.cohorts?.dolphin || []).find(r => r.date === ds) || {};
          const minnow  = (forecast?.cohorts?.minnow  || []).find(r => r.date === ds) || {};
          const d = new Date(ds);
          const DOW = ["Sun","Mon","Tue","Wed","Thu","Fri","Sat"][d.getDay()];
          return {
            date:     `${d.getDate()}/${d.getMonth()+1} (${DOW})`,
            forecast: (whale.forecast||0) + (dolphin.forecast||0) + (minnow.forecast||0),
            lower:    (whale.lower||0)    + (dolphin.lower||0)    + (minnow.lower||0),
            upper:    (whale.upper||0)    + (dolphin.upper||0)    + (minnow.upper||0),
            conf:     whale.confidence || "–",
            is_event: whale.is_event || dolphin.is_event || minnow.is_event,
          };
        });
      })()
    : [];

  const alertList = alerts?.alerts || [];

  return (
    <div style={{
      fontFamily: "'JetBrains Mono','SF Mono','Fira Code',monospace",
      color: "#d0d0d0", background: "#0c0c0e",
      maxWidth: 760, margin: "0 auto", padding: "24px 16px",
    }}>

      {/* Header */}
      <div style={{ borderBottom: "1px solid rgba(255,255,255,0.06)", paddingBottom: 20, marginBottom: 28 }}>
        <div style={{ display: "flex", alignItems: "baseline", gap: 12, marginBottom: 6 }}>
          <span style={{ fontSize: 11, fontWeight: 700, color: "#EF9F27", letterSpacing: 2, textTransform: "uppercase" }}>KTO</span>
          <span style={{ fontSize: 11, color: "#555" }}>Kim Thánh Online</span>
        </div>
        <div style={{ fontSize: 24, fontWeight: 700, color: "#f0f0f0", letterSpacing: -0.5, marginBottom: 6 }}>
          Daily spending baseline
        </div>
        <div style={{ display: "flex", gap: 16, fontSize: 11, color: "#555", flexWrap: "wrap" }}>
          <span>Report: {reportDate}</span>
          <span style={{ color: "#333" }}>|</span>
          <span>Data: {dataDate} (D-1)</span>
          <span style={{ color: "#333" }}>|</span>
          <span>Model: ETS Holt-Winters · weekly seasonality</span>
        </div>
      </div>

      {/* S1: Health check */}
      <div style={{ marginBottom: 32 }}>
        <SectionHead num="1" title="Yesterday's health check" desc="Actual Gold spent vs. ETS baseline. Is the economy behaving normally?" color="#85B7EB" />
        <div style={{ display: "flex", gap: 10, flexWrap: "wrap" }}>
          <MetricCard label="Actual spend"   value={fmt(ydActual)}   sub="All cohorts · Gold" />
          <MetricCard label="Baseline (P50)" value={fmt(ydBaseline)} sub="ETS predicted" />
          <MetricCard label="Deviation"      value={`${deviation}%`} accent={devColor}
            sub={isNaN(devAbs) ? "–" : Math.abs(devAbs) < 15 ? "Within ±15% band" : "Outside band"} />
          <MetricCard label="Spender count"  value={totalSpenders.toLocaleString()} sub="Active Gold spenders" />
        </div>
      </div>

      {/* S2: Cohort breakdown */}
      <div style={{ marginBottom: 32 }}>
        <SectionHead num="2" title="Cohort breakdown" desc="Which segment is driving the deviation? Spender headcount and per-role average." color="#AFA9EC" />
        <Card>
          <div style={{ display: "grid", gridTemplateColumns: "minmax(0,1.2fr) repeat(5,minmax(0,1fr))", padding: "10px 16px", fontSize: 10, fontWeight: 600, color: "#555", textTransform: "uppercase", letterSpacing: 0.5, borderBottom: "1px solid rgba(255,255,255,0.06)" }}>
            <span>Cohort</span><span style={{textAlign:"right"}}>Spend</span><span style={{textAlign:"right"}}>Velocity</span><span style={{textAlign:"right"}}>Avg/role</span><span style={{textAlign:"right"}}>Spenders</span><span style={{textAlign:"right"}}>vs Base</span>
          </div>
          {cohortRows.map((r, i) => {
            const dev = r.baseline_p50 ? ((r.total_gold_spent - r.baseline_p50) / r.baseline_p50 * 100) : null;
            return (
              <div key={i} style={{ display: "grid", gridTemplateColumns: "minmax(0,1.2fr) repeat(5,minmax(0,1fr))", padding: "12px 16px", fontSize: 13, alignItems: "center", borderBottom: i < 2 ? "1px solid rgba(255,255,255,0.06)" : "none" }}>
                <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                  <div style={{ width: 8, height: 8, borderRadius: 3, background: r.c.color }} />
                  <span style={{ fontWeight: 600, color: "#e0e0e0" }}>{r.c.label}</span>
                  <span style={{ fontSize: 10, color: "#555" }}>{r.c.vip}</span>
                </div>
                <span style={{ textAlign: "right", color: "#ccc" }}>{fmt(r.total_gold_spent)}</span>
                <span style={{ textAlign: "right", color: r.balance_velocity < 0.4 ? "#F0997B" : "#ccc" }}>
                  {r.balance_velocity != null ? r.balance_velocity.toFixed(2) : "–"}
                </span>
                <span style={{ textAlign: "right", color: "#999" }}>{fmt(r.avg_spend_per_role)}</span>
                <span style={{ textAlign: "right", color: "#999" }}>
                  {(r.active_spenders || 0).toLocaleString()}
                  {r.new_spenders > 0 && <span style={{ fontSize: 10, color: "#5DCAA5", marginLeft: 4 }}>+{r.new_spenders}</span>}
                </span>
                <span style={{ textAlign: "right", fontWeight: 600, color: dev == null ? "#555" : dev > 0 ? "#5DCAA5" : dev < -10 ? "#F0997B" : "#888" }}>
                  {dev != null ? (dev > 0 ? "+" : "") + dev.toFixed(1) + "%" : "–"}
                </span>
              </div>
            );
          })}
        </Card>
      </div>

      {/* S3: 30-day trend */}
      <div style={{ marginBottom: 32 }}>
        <SectionHead num="3" title="30-day trend" color="#85B7EB" />
        <div style={{ display: "flex", gap: 16, fontSize: 11, color: "#555", marginBottom: 10, paddingLeft: 32 }}>
          <span><span style={{ color: "#85B7EB" }}>—</span> actual</span>
          <span><span style={{ color: "#85B7EB", opacity: 0.4 }}>- -</span> baseline</span>
          <span style={{ color: "#5DCAA5" }}>● over</span>
          <span style={{ color: "#F0997B" }}>● under</span>
          <span style={{ color: "#EF9F27" }}>■ event</span>
        </div>
        <Card style={{ padding: "16px 12px 8px" }}>
          {trendData && trendData.length > 1 ? <TrendChart data={trendData} /> : (
            <div style={{ color: "#444", textAlign: "center", padding: 32 }}>Not enough data for trend chart (need 30+ days)</div>
          )}
        </Card>
      </div>

      {/* S4: Velocity & Spender sparklines */}
      <div style={{ marginBottom: 32 }}>
        <SectionHead num="4" title="Velocity & spender trends (7-day)" desc="Left: balance velocity (% Gold used). Right: spender headcount." color="#F0997B" />
        <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
          {velData && velData.map((v, i) => {
            const sp = spenderData[i];
            const latestVel = v.vals.filter(x => x != null).slice(-1)[0];
            const latestSp  = sp.vals.filter(x => x != null).slice(-1)[0];
            const latestNew = sp.newVals.filter(x => x != null).slice(-1)[0];
            return (
              <div key={i} style={{ display: "flex", gap: 10 }}>
                <Card style={{ flex: 1, padding: "12px 16px", ...(v.trend === "declining" ? { borderColor: v.c.color + "33" } : {}) }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 6 }}>
                    <div style={{ width: 8, height: 8, borderRadius: 3, background: v.c.color }} />
                    <span style={{ fontSize: 12, fontWeight: 600, color: "#ccc" }}>{v.c.label}</span>
                    <span style={{ fontSize: 10, color: "#555", marginLeft: "auto" }}>velocity</span>
                  </div>
                  <div style={{ display: "flex", alignItems: "baseline", gap: 6, marginBottom: 4 }}>
                    <span style={{ fontSize: 20, fontWeight: 700, color: v.trend === "declining" ? v.c.color : "#e0e0e0" }}>
                      {latestVel != null ? latestVel.toFixed(2) : "–"}
                    </span>
                    <span style={{ fontSize: 10, padding: "2px 6px", borderRadius: 4, fontWeight: 600, background: v.trend === "declining" ? v.c.color + "18" : "rgba(255,255,255,0.04)", color: v.trend === "declining" ? v.c.color : "#666" }}>
                      {v.trend}
                    </span>
                  </div>
                  <Spark vals={v.vals} color={v.c.color} />
                </Card>
                <Card style={{ flex: 1, padding: "12px 16px" }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 6 }}>
                    <div style={{ width: 8, height: 8, borderRadius: 3, background: v.c.color, opacity: 0.5 }} />
                    <span style={{ fontSize: 12, fontWeight: 600, color: "#ccc" }}>{v.c.label}</span>
                    <span style={{ fontSize: 10, color: "#555", marginLeft: "auto" }}>spenders</span>
                  </div>
                  <div style={{ display: "flex", alignItems: "baseline", gap: 6, marginBottom: 4 }}>
                    <span style={{ fontSize: 20, fontWeight: 700, color: "#e0e0e0" }}>
                      {latestSp != null ? latestSp.toLocaleString() : "–"}
                    </span>
                    {latestNew > 0 && <span style={{ fontSize: 10, color: "#5DCAA5", fontWeight: 600 }}>+{latestNew} new</span>}
                  </div>
                  <Spark vals={sp.vals} color={v.c.color + "88"} />
                </Card>
              </div>
            );
          })}
        </div>
      </div>

      {/* S5: Gold sinks placeholder (needs shop_breakdown data) */}
      <div style={{ marginBottom: 32 }}>
        <SectionHead num="5" title="Gold sinks by shop" desc="Where Gold was spent — from logway group breakdown. Transfers excluded." color="#EF9F27" />
        <Card style={{ padding: "20px 16px" }}>
          <div style={{ fontSize: 12, color: "#555", textAlign: "center" }}>
            Shop breakdown requires <code>data/shop_breakdown.csv</code> — generated by pipeline when
            the <code>shop_breakdown.sql</code> query runs.
          </div>
        </Card>
      </div>

      {/* S6: Alerts */}
      <div style={{ marginBottom: 32 }}>
        <SectionHead num="6" title="Alerts & signals" desc="Pattern-based warnings combining spend, velocity, and spender trends across multiple days." color="#F0997B" />
        {alertList.length === 0 ? (
          <Card style={{ padding: "16px", fontSize: 12, color: "#555", textAlign: "center" }}>
            No active alerts — all metrics within normal range.
          </Card>
        ) : (
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            {alertList.map((a, i) => {
              const colors = {
                warning: { bg: "rgba(240,153,123,0.06)", border: "rgba(240,153,123,0.15)", icon: "#F0997B", sym: "!" },
                success: { bg: "rgba(93,202,165,0.06)",  border: "rgba(93,202,165,0.15)",  icon: "#5DCAA5", sym: "✓" },
                info:    { bg: "rgba(133,183,235,0.04)", border: "rgba(133,183,235,0.1)",  icon: "#85B7EB", sym: "i" },
              }[a.type] || { bg: "rgba(255,255,255,0.03)", border: "rgba(255,255,255,0.06)", icon: "#666", sym: "·" };
              const co = a.cohort ? COHORTS.find(c => c.id === a.cohort) : null;
              return (
                <div key={i} style={{ display: "flex", gap: 12, padding: "12px 16px", borderRadius: 10, alignItems: "flex-start", background: colors.bg, border: `1px solid ${colors.border}` }}>
                  <div style={{ width: 20, height: 20, borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 11, fontWeight: 700, flexShrink: 0, background: colors.border, color: colors.icon }}>{colors.sym}</div>
                  <div style={{ fontSize: 12, lineHeight: 1.6, color: "#999" }}>
                    {co && <span style={{ fontSize: 10, fontWeight: 600, padding: "2px 6px", borderRadius: 4, marginRight: 6, background: co.bg, color: co.color, border: `1px solid ${co.border}` }}>{co.label}</span>}
                    <strong style={{ color: "#ccc" }}>{a.title}: </strong>{a.message}
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* S7: 7-day forecast */}
      <div style={{ marginBottom: 32 }}>
        <SectionHead num="7" title="7-day forecast" desc="ETS projection. Event multiplier applied where scheduled. Confidence widens each day." color="#AFA9EC" />
        {forecastRows.length === 0 ? (
          <Card style={{ padding: 16, fontSize: 12, color: "#555", textAlign: "center" }}>
            Forecast not yet generated — run <code>python pipeline/build_baseline.py</code>.
          </Card>
        ) : (
          <Card>
            <div style={{ display: "grid", gridTemplateColumns: "minmax(0,1.4fr) repeat(4,minmax(0,1fr))", padding: "10px 16px", fontSize: 10, fontWeight: 600, color: "#555", textTransform: "uppercase", letterSpacing: 0.5, borderBottom: "1px solid rgba(255,255,255,0.06)" }}>
              <span>Date</span><span style={{textAlign:"right"}}>Forecast</span><span style={{textAlign:"right"}}>Lower</span><span style={{textAlign:"right"}}>Upper</span><span style={{textAlign:"right"}}>Conf.</span>
            </div>
            {forecastRows.map((f, i) => (
              <div key={i} style={{ display: "grid", gridTemplateColumns: "minmax(0,1.4fr) repeat(4,minmax(0,1fr))", padding: "10px 16px", fontSize: 12, alignItems: "center", borderBottom: i < forecastRows.length - 1 ? "1px solid rgba(255,255,255,0.06)" : "none", background: f.is_event ? "rgba(239,159,39,0.04)" : "transparent" }}>
                <span style={{ fontWeight: 500, color: "#ccc" }}>
                  {f.date}
                  {f.is_event && <span style={{ fontSize: 9, padding: "2px 5px", borderRadius: 4, marginLeft: 6, background: "rgba(239,159,39,0.12)", color: "#EF9F27", fontWeight: 600 }}>EVENT</span>}
                </span>
                <span style={{ textAlign: "right", color: "#ddd" }}>{fmt(f.forecast)}</span>
                <span style={{ textAlign: "right", color: "#555" }}>{fmt(f.lower)}</span>
                <span style={{ textAlign: "right", color: "#555" }}>{fmt(f.upper)}</span>
                <span style={{ textAlign: "right", fontSize: 11, color: i > 4 ? "#F0997B" : "#666" }}>{f.conf}</span>
              </div>
            ))}
          </Card>
        )}
        <div style={{ fontSize: 10, color: "#444", marginTop: 8, paddingLeft: 32 }}>
          Beyond day 14 → switch to scenario planning (see docs/project_spec.md §6.4)
        </div>
      </div>

      {/* Footer */}
      <div style={{ fontSize: 10, color: "#333", borderTop: "1px solid rgba(255,255,255,0.04)", paddingTop: 14, lineHeight: 1.8 }}>
        <span style={{ color: "#555" }}>src</span> hive.kto_658 · moneychange_reduce + moneychange_add + recharge_deliver<br />
        <span style={{ color: "#555" }}>filter</span> moneytype=Gold · price/100 · exclude LogWay_Trade, MarketStall transfers (bigtype 21,37–43)<br />
        <span style={{ color: "#555" }}>cohort</span> Whale VIP≥12 · Dolphin VIP 7–11 · Minnow VIP 0–6<br />
        <span style={{ color: "#555" }}>model</span> ETS Holt-Winters · α=0.2 (optimized) · weekly seasonality · event windows excluded from training
      </div>
    </div>
  );
}

ReactDOM.createRoot(document.getElementById("root")).render(React.createElement(Dashboard));
